#image: maven:3.9.9-eclipse-temurin-23
#
#stages:
#  - setup
#  - build
#  - deploy
#
#variables:
#  POSTGRES_DB: db1
#  POSTGRES_USER: postuser
#  POSTGRES_PASSWORD: 5454
#  POSTGRES_HOST: postgres
#  POSTGRES_PORT: 5432
#
#services:
#  - name: postgres:latest
#    alias: postgres
#
#maven-build:
#  stage: build
#  script:
#    - mvn package -B
#  artifacts:
#    paths:
#      - target/*.jar
image: maven:3.8.6-openjdk-17

services:
  - postgres:latest

variables:
  POSTGRES_DB: db1
  POSTGRES_USER: postuser
  POSTGRES_PASSWORD: "5454"
  POSTGRES_HOST_AUTH_METHOD: trust
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db1
  SPRING_DATASOURCE_USERNAME: postuser
  SPRING_DATASOURCE_PASSWORD: 5454

stages:
  - build
  - test

before_script:
  - echo "Waiting for PostgreSQL to be ready..."
  - until pg_isready -h postgres -p 5432 -U $POSTGRES_USER; do sleep 2; done
  - echo "PostgreSQL is ready!"

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test
