image: maven:3.9.9-eclipse-temurin-23

stages:
  - setup
  - build
  - deploy

variables:
  DB_HOST: localhost
  DB_PORT: 5433
  SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5433/db1"
  SPRING_DATASOURCE_USERNAME: postuser
  SPRING_DATASOURCE_PASSWORD: 5454

services:
  - docker:dind

before_script:
  - echo "Starting Docker Compose..."
  - docker-compose up -d
  - echo "Waiting for PostgreSQL to be ready..."
  - until docker exec $(docker ps -q -f name=db) pg_isready -h localhost -p 5432; do sleep 5; done

maven-build:
  stage: build
  script:
    - mvn package -B
  artifacts:
    paths:
      - target/gitlab-ci-demo.jar
