stages:
  - setup
  - build
  - deploy

default:
  services:
      - postgres:latest
variables:
  POSTGRES_DB: db1
  POSTGRES_USER: postuser
  POSTGRES_PASSWORD: 5454
  ports: "5433:5432"

maven-build:
  image: maven:3.9.9-eclipse-temurin-23
  stage: build
  script:
    - mvn package -B
  artifacts:
    paths:
      - target/gitlab-ci-demo.jar
